# docker-compose-dev.yml
services:

  pgsql-ticket:
    image: postgres:17.6
    ports:
      # HOST:CONTAINER
      - "9876:5432"
    environment:
      - POSTGRES_PASSWORD=pgsql-ticket-password 
      - POSTGRES_USER=pgsql-ticket-master     
    networks:
      - backend
    volumes:
      # Scripts de criação dos bancos de dados
      # - ./01-create-database-users.sql:/docker-entrypoint-initdb.d/01-create-database-users.sql
      - ./02-create-database-sales.sql:/docker-entrypoint-initdb.d/02-create-database-sales.sql
      # - ./03-create-database-notifications.sql:/docker-entrypoint-initdb.d/03-create-database-notifications.sql
      
      - ../pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgsql-ticket-master -d tickets-sales"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9.8.0
    ports:
      - "8123:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=web@ufop.edu.br
      - PGADMIN_DEFAULT_PASSWORD=123456
    networks:
      - backend
    depends_on:
      - pgsql-ticket
  tickets-app:
    build: 
        context: ../tickets
        dockerfile: Dockerfile
    image: tickets-microservice 
    ports:
      - "4000:4000"
    networks:
      - backend
      
    depends_on:
      pgsql-ticket:
        condition: service_healthy

    environment:
      - SERVER_PORT=4000
      
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgsql-ticket:5432/tickets-sales
      
      - SPRING_DATASOURCE_USERNAME=pg-tickets-sales
      - SPRING_DATASOURCE_PASSWORD=tickets-sales-password
      
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true

    volumes:
      - ../tickets/src:/app/src

networks:
  frontend:
  backend: